api/swagger.yaml
closes #13
OK, checking this in again with JUST the spec (no generated code). I put the spec in the same place that SwaggerHub put it for compatibility in the future.
Please review just the spec -- maybe it gets merged into main as the first real commit?
=> Create api spec

.gitignore, pom.xml, src/main/java/ca/bc/gov/api/core/configuration/OraclePersistenceConfiguration.java, src/main/java/ca/bc/gov/api/core/configuration/SwaggerConfiguration.java, src/main/java/ca/bc/gov/api/core/repository/CoreRepository.java, src/main/java/ca/bc/gov/api/core/util/impl/CoreUtilImpl.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/controller/LegacyClientController.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/dao/ClientPublicViewDao.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/dao/impl/ClientPublicViewDaoImpl.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/entity/ClientPublicViewEntity.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/entity/ClientStatusCodeEntity.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/entity/ClientTypeCodeEntity.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/repository/ClientPublicViewRepository.java, src/main/java/ca/bc/gov/api/m/oracle/legacyclient/service/impl/LegacyClientServiceImpl.java, src/test/java/ca/bc/gov/api/m/oracle/legacyclient/controller/LegacyClientControllerTest.java, src/test/java/ca/bc/gov/api/m/oracle/legacyclient/service/impl/LegacyClientServiceImplTest.java
Upgrade to Spring Boot 3 and optimized imports
Fixes [FSADT1-489](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-489)
No new testes were needed
=> Merge #59: feat: Upgrade Spring Boot to version 3.0.0

.github/workflows/merge-main.yml
Fixing an issue with merge-main workflow
=> fix: workflow merge-main

openshift.deploy.yml
Fixing parameters for deployment
---
[API](https://nr-forest-client-api-97-backend.apps.silver.devops.gov.bc.ca/) available
=> ci: fixing deployment parameters

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, openshift.deploy.yml
Removing unwanted parameters from the deployment
---
[API](https://nr-forest-client-api-98-backend.apps.silver.devops.gov.bc.ca/) available
=> fix(FSADT1-499): fixing deploy parameters

.github/workflows/merge-main.yml, .github/workflows/unit-tests.yml, Dockerfile, src/main/resources/application.yml
Changing release workflow for main.
---
[API](https://nr-forest-client-api-100-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: gateway and release

.github/workflows/merge-main.yml
Fix production deploy flow
---
[API](https://nr-forest-client-api-102-backend.apps.silver.devops.gov.bc.ca/) available
=> ci: fix prod release flow

.github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, src/main/java/ca/bc/gov/api/oracle/legacy/entity/ClientDoingBusinessAsEntity.java, src/main/java/ca/bc/gov/api/oracle/legacy/exception/ClientNotFoundException.java, src/main/java/ca/bc/gov/api/oracle/legacy/exception/NoSearchParameterFound.java, src/main/java/ca/bc/gov/api/oracle/legacy/handlers/ClientAcronmHandler.java, src/main/java/ca/bc/gov/api/oracle/legacy/handlers/ClientAcronymHandler.java, src/main/java/ca/bc/gov/api/oracle/legacy/repository/ClientDoingBusinessAsRepository.java, src/main/java/ca/bc/gov/api/oracle/legacy/routes/ClientRouter.java, src/main/java/ca/bc/gov/api/oracle/legacy/service/ClientService.java, src/test/java/ca/bc/gov/api/oracle/legacy/handlers/ClientHandlerTest.java
Adding search by acronym functionality
Fixes #119 
Integration tests
Also including PRs #118 and also  #117
---
[API](https://nr-forest-client-api-120-backend.apps.silver.devops.gov.bc.ca/) available
=> feat(FSADT1-662): adding search by acronym

.github/workflows/merge-main.yml
---
[API](https://nr-forest-client-api-125-backend.apps.silver.devops.gov.bc.ca/) available
=> ci: fixing smoke test params

.github/dependabot.yml, .github/workflows/merge-main.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml
---
[API](https://nr-forest-client-api-128-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: deploy and smoke

.github/workflows/merge-main.yml
Fixing image promotion to prod
---
[API](https://nr-forest-client-api-132-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: promoting image to prod

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, .github/workflows/unit-tests.yml
Adding tagging to the release
Adding tagging as a first step to have a controlled release process
---
[API](https://nr-forest-client-api-136-backend.apps.silver.devops.gov.bc.ca/) available
=> feat: adding tagging

.github/workflows/merge-main.yml
---
[API](https://nr-forest-client-api-137-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: fixing release

.github/workflows/merge-main.yml
---
[API](https://nr-forest-client-api-138-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: fixing release image promotion

.github/workflows/merge-main.yml, openshift.deploy.yml
---
[API](https://nr-forest-client-api-139-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: fixing workflow

.github/workflows/merge-main.yml, openshift.deploy.yml
---
[API](https://nr-forest-client-api-141-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: promotion and memory

.github/workflows/merge-main.yml
Fixing an issue on the workflow due to conflict on rebase
---
[API](https://nr-forest-client-api-142-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: fixing workflow issue

Dockerfile, openshift.deploy.yml, startup.sh
---
[API](https://nr-forest-client-api-150-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: init container

src/main/java/ca/bc/gov/api/oracle/legacy/controller/ClientController.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientPublicViewDto.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientStatusCodeEnum.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientTypeCodeEnum.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientViewDto.java, src/main/java/ca/bc/gov/api/oracle/legacy/entity/ForestClientBaseEntity.java, src/main/java/ca/bc/gov/api/oracle/legacy/entity/ForestClientEntity.java, src/main/java/ca/bc/gov/api/oracle/legacy/repository/ForestClientRepository.java, src/main/java/ca/bc/gov/api/oracle/legacy/service/ClientService.java, src/main/java/ca/bc/gov/api/oracle/legacy/util/ClientMapper.java, src/test/java/ca/bc/gov/api/oracle/legacy/controller/ClientControllerIntegrationTest.java
General search api, which will allow us to provide either a name (client name) or a forest client number, and the api will return all the possible results based on a wildcard search
---
[API](https://nr-forest-client-api-156-backend.apps.silver.devops.gov.bc.ca/) available
---
[API](https://nr-forest-client-api-156-backend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will …
=> [FSADT1-748] Create general search API

.github/workflows/pr-open.yml, Dockerfile, openshift.deploy.yml, pom.xml, src/main/java/ca/bc/gov/api/oracle/legacy/controller/ClientController.java, src/main/java/ca/bc/gov/api/oracle/legacy/entity/ClientLocationEntity.java, src/main/java/ca/bc/gov/api/oracle/legacy/repository/ClientLocationRepository.java, src/main/java/ca/bc/gov/api/oracle/legacy/service/ClientLocationService.java, src/test/java/ca/bc/gov/api/oracle/legacy/controller/ClientLocationControllerIntegrationTest.java
Adding location details endpoint
---
[API](https://nr-forest-client-api-174-backend.apps.silver.devops.gov.bc.ca/) available
=> feat(FSADT1-846): adding location details

src/main/java/ca/bc/gov/api/oracle/legacy/configuration/SwaggerConfiguration.java, src/main/java/ca/bc/gov/api/oracle/legacy/controller/ClientController.java
Adding header for API key on swagger
---
[API](https://nr-forest-client-api-181-backend.apps.silver.devops.gov.bc.ca/) available
=> fix: adding missing api key header

Dockerfile
---
[API](https://nr-forest-client-api-182-backend.apps.silver.devops.gov.bc.ca/) available
=> chore: forcing release

.github/workflows/merge-main.yml, .github/workflows/unit-tests.yml
Two other PRs are blocked on or around Trivy.  This is an attempt to fix that.
---
[API](https://nr-forest-client-api-186-backend.apps.silver.devops.gov.bc.ca/) available
=> deps: bump Trivy action

.github/pull_request_template.md, .gitignore, config/application-local.yml, config/application.yml, postman/FCA.postman_collection.json, src/main/java/ca/bc/gov/api/oracle/legacy/ApplicationConstants.java, src/main/java/ca/bc/gov/api/oracle/legacy/controller/ClientController.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientPublicViewDto.java, src/main/java/ca/bc/gov/api/oracle/legacy/dto/ClientViewDto.java, src/main/java/ca/bc/gov/api/oracle/legacy/entity/ForestClientEntity.java, src/main/java/ca/bc/gov/api/oracle/legacy/repository/ForestClientRepository.java, src/main/java/ca/bc/gov/api/oracle/legacy/service/ClientService.java, src/main/java/ca/bc/gov/api/oracle/legacy/util/ClientMapper.java, src/test/java/ca/bc/gov/api/oracle/legacy/service/ClientServiceIntegrationTest.java
Added a header called `X-Total-Count` to all list/flux endpoints to provide the total amount of results that this request can provide.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
[API](https://nr-forest-client-api-198-backend.apps.silver.devops.gov.bc.ca/) available
=> feat(FSADT1-1096): adding count header

.github/workflows/merge-main.yml, src/main/resources/static/robots.txt
---
[API](https://nr-forest-client-api-203-backend.apps.silver.devops.gov.bc.ca/) available
=> ci: disabling pentest

.github/workflows/pr-close.yml
Missed a commented line.
---
[API](https://nr-forest-client-api-207-backend.apps.silver.devops.gov.bc.ca/) available
=> chore(ci): clean up commented line

.github/openshift.dev.yml, .github/workflows/api-check.yml, .github/workflows/pr-open.yml, openshift.deploy.yml
Removing open URLs from the API to avoid unwanted access to the API
---
[API](https://nr-forest-client-api-210-backend.apps.silver.devops.gov.bc.ca/) available
=> feat(FSADT1-679): disabling openshift routes

openshift.deploy.yml, pom.xml, src/main/java/ca/bc/gov/api/oracle/legacy/Application.java, src/main/java/ca/bc/gov/api/oracle/legacy/configuration/MetricConfiguration.java, src/main/java/ca/bc/gov/api/oracle/legacy/configuration/TracingConfiguration.java, src/main/resources/application.yml, src/test/java/ca/bc/gov/api/oracle/legacy/AbstractTestContainerIntegrationTest.java, src/test/resources/application-default.yml
- fixed a CVE-2024-22259 related to uncontrolled redirect
- updated and allowed metrics scrapping
- added tracing configuration
- formatted log files to be json
- 
Fixes #211 
---
[API](https://nr-forest-client-api-212-backend.apps.silver.devops.gov.bc.ca/) available
=> feat: metrics, tracing and CVE fixes

.github/workflows/api-check.yml, src/main/java/ca/bc/gov/api/oracle/legacy/ApplicationConstants.java
---
[API](https://nr-forest-client-api-230-backend.apps.silver.devops.gov.bc.ca/) available
=> chore: changing check to happen every hour

.github/gwa/service-prod.yaml, .github/gwa/service-test.yaml
---
[API](https://nr-forest-client-api-248-api.apps.silver.devops.gov.bc.ca/) available
=> fix: fixing api route

src/main/java/ca/bc/gov/api/oracle/legacy/ApplicationConstants.java
---
[API](https://nr-forest-client-api-249-api.apps.silver.devops.gov.bc.ca/) available
=> chore: force release

.github/workflows/pr-open.yml, src/main/resources/application.properties
---
[API](https://nr-forest-client-api-263-api.apps.silver.devops.gov.bc.ca/) available
=> chore(ci): Simplify app version format in pr-open.yml workflow

src/main/java/ca/bc/gov/api/oracle/legacy/controller/ClientSearchController.java, src/main/java/ca/bc/gov/api/oracle/legacy/repository/ForestClientRepository.java, src/main/java/ca/bc/gov/api/oracle/legacy/service/ClientSearchService.java, src/test/java/ca/bc/gov/api/oracle/legacy/controller/ClientSearchControllerIntegrationTest.java
Added a new endpoint for search
---
[API](https://nr-forest-client-api-269-api.apps.silver.devops.gov.bc.ca/) available
=> feat(FSADI1-1650): added new search endpoint

.github/workflows/pr-open.yml
---
[API](https://nr-forest-client-api-280-api.apps.silver.devops.gov.bc.ca/) available
=> chore(ci): use GH runner ubuntu-24.04

.github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/reusable-tests-be.yml
---
[API](https://nr-forest-client-api-279-api.apps.silver.devops.gov.bc.ca/) available
=> chore(ci): actions moved to bcgov org

.github/workflows/pr-open.yml
---
[API](https://nr-forest-client-api-281-api.apps.silver.devops.gov.bc.ca/) available
=> chore(ci): remove JS handling from workflow conditionals

pom.xml, src/main/resources/application.yml
---
[API](https://nr-forest-client-api-300-api.apps.silver.devops.gov.bc.ca/) available
=> chore(be): Upgraded ojdbc11 oracle driver

.github/workflows/pr-close.yml
---
[API](https://nr-forest-client-api-309-api.apps.silver.devops.gov.bc.ca/) available
=> ci: fixing version

pom.xml
---
[API](https://nr-forest-client-api-340-api.apps.silver.devops.gov.bc.ca/) available
=> chore: Fixed vulnerability CVE-2025-22227

.github/workflows/api-check.yml, .github/workflows/merge.yml, .github/workflows/pr-open.yml, .github/workflows/reusable-tests-be.yml, .github/workflows/reusable-tests-repo.yml
Reverts bcgov/nr-forest-client-api#365
---
[API](https://nr-forest-client-api-366-api.apps.silver.devops.gov.bc.ca/) available
=> chore: Revert "chore(deps): update github actions"

pom.xml
Fixing CVE-2025-58057. Netty is an asynchronous event-driven network application framework for rapid development of maintainable high performance protocol servers & clients. In netty-codec-compression versions 4.1.124.Final and below, and netty-codec versions 4.2.4.Final and below, when supplied with specially crafted input, BrotliDecoder and certain other decompression decoders will allocate a large number of reachable byte buffers, which can lead to denial of service. BrotliDecoder.decompress has no limit in how often it calls pull, decompressing data 64K bytes at a time. The buffers are saved in the output list, and remain reachable until OOM is hit. This is fixed in versions 4.1.125.Final of netty-codec and 4.2.5.Final of netty-codec-compression.
---
Any successful …
=> fix(sec:CVE-2025-58057): Netty's BrotliDecoder is vulnerable to DoS
